services:
  portfolio:
    image: ghcr.io/djelines/portfolio:latest
    container_name: portfolio_ines
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    ports:
      - "9927:9927" 
    restart: always
    networks:
      - reseau_partage
networks:
  reseau_partage:
    external: true
    name: global_network  